### ISSUE TITLE
Provide (or document) an option to ignore directories

### ISSUE THREAD

**Issue by KasparEtter** [jhotmann/node-rename-cli#11]
This issue started out as a wish for an enhancement, but, as it turned out, it's also a bug.

When renaming files with `rename '*'` or `rename '**/*'`, I would like to be able to only rename files but not directories without enforcing any naming conventions. My current workaround is to use `rename '**/*.*'` because my directories rarely contain periods while all the files I'm interested in typically have a suffix.

Now to the bug part: If you rename with `'**/*'` files in a subdirectory and the directory itself is also renamed (due to the "limitation" described above), then the command fails on all files in the subdirectory with `<filepath> does not exist! Operation skipped.`. Ideally, the tool would either rename directories last or keep track of the renames dynamically.

**Comment by jhotmann** [comment]
Fixed in 6.1.0

**Comment by KasparEtter** [comment]
Just for the record: Once #18 is merged to restore previous directory handling, nested renaming _including_ directories (i.e. without using `-d`) still fails with `<filepath> does not exist! Operation skipped.`. I leave it up to you whether you want to address this (and reopen this issue until then) or whether the "workaround" (with `-d`) is good enough. It is good enough for me, it's just not very user-friendly (but probably not trivial to fix). And you wouldn't be able to rename nested directories if you wanted to do so. (An option like `--only-directories` wouldn't solve this without addressing the underlying problem.)
